@Library('jenkins-pipeline-library@main') _

pipeline {
  agent {
    node {
      label 'openstack-slave-pangyo-site-prepare'
      customWorkspace "workspace/${env.JOB_NAME}/${env.BUILD_NUMBER}"
    }
  }
  parameters {
    string(name: 'TACOPLAY_VERSION',
      defaultValue: 'main',
      description: 'branch or tag of tacoplay (Eg, \'main\' or \'2.0.0\'')
    string(name: 'TACOPLAY_SITE',
      defaultValue: 'gate-centos-lb-ceph-offline-multinodes',
      description: 'tacoplay site (inventory) name in tago-gate-inventories repository')
    string(name: 'TARGET_SITE',
      defaultValue: 'hanu-reference',
      description: 'target site (inventory) name for manifest preparation')
    string(name: 'INCLUDED_APPS',
      defaultValue: 'openstack,lma,service-mesh',
      description: 'Apps to include in tarball? (comma-separated list)')
    string(name: 'OPENSTACK_RELEASE',
      defaultValue: 'stein',
      description: 'openstack_release for manifest selection (Eg, \'queens\' or \'stein\'')
  }
  environment {
    KUBECONFIG = "/root/.kube/config"
    ANSIBLE_INVALID_TASK_ATTRIBUTE_FAILED = "False"
  }
  options {
    timeout(time: 240, unit: 'MINUTES')
    timestamps()
  }

  stages {
    stage ('Run') {
      steps {
          script {
            sh """
	      git clone git@github.com:openinfradev/taco-gate-inventories.git --single-branch
              git clone https://github.com/openinfradev/tacoplay.git
              cp -r taco-gate-inventories/inventories/${params.TACOPLAY_SITE} tacoplay/inventory
              cp -r taco-gate-inventories/inventories/preparation tacoplay/inventory
              mkdir /opt/jenkins/agent/docker_images || true

            """
            dir('tacoplay') {
              sh "git checkout ${params.TACOPLAY_VERSION}"

              // Should pass this format: '{"taco_apps": ['openstack','lma']}'
              tacoplay_params = "-e '{\"taco_apps\": ["
              add_openstack_param = false

              if (params.INCLUDED_APPS) {
                def app_list = params.INCLUDED_APPS.split(',')

                app_list.eachWithIndex { app, index ->
                  if ( app == 'openstack') {
                    if (! params.TARGET_SITE.startsWith('gate')) {
                      add_openstack_param = true
                    }
                  }

                  if ( index == app_list.length-1 ) {
                    tacoplay_params += "'${app}'"
                  } else {
                   tacoplay_params += "'${app}',"
                  }
                }
              }
              tacoplay_params += "]}'"

              if (add_openstack_param) {
                tacoplay_params += " -e 'site_name=${params.TARGET_SITE} openstack_release=${params.OPENSTACK_RELEASE}'"
              }

              println("tacoplay_params: ${tacoplay_params}")

              sh """
                env | grep PATH
                ./fetch-sub-projects.sh
                python --version
		sudo pip3 install --upgrade pip
		sudo pip3 install -r requirements.txt --upgrade --ignore-installed

                ansible-playbook -vvv -u root -b -i inventory/preparation/local.ini extra-playbooks/site-prepare.yml --tags download,upload,preinstall --skip-tags upgrade -e @inventory/preparation/extra-vars.yml -e site_name=${params.TARGET_SITE} ${tacoplay_params}
              """
            }
          }
      }
    }

    stage ('Push artifact') {
      steps {
          script {
            sh """
              mv tacoplay.tar.gz tacoplay-${params.TARGET_SITE}-${params.TACOPLAY_VERSION}-\$(date +%y%m%d).tar.gz
              mc --quiet cp tacoplay-${params.TARGET_SITE}-${params.TACOPLAY_VERSION}-\$(date +%y%m%d).tar.gz tacorepo/tacoplay-artifacts/

              echo "tacoplay-${params.TARGET_SITE}-${params.TACOPLAY_VERSION}-\$(date +%y%m%d).tar.gz" > latest-${params.TARGET_SITE}
              mc --quiet cp latest-${params.TARGET_SITE} tacorepo/tacoplay-artifacts/
            """
          }
      }
    }

  }

  post {
    success {
      notifyCompleted(true)
    }
    failure {
      notifyCompleted(false)
    }
  }
}
